version: "3.9"
services:
    nginx:
        image: "nginx:alpine"
        restart: always
        working_dir: /app
        links:
            - php-fpm
        volumes:
            - ".:/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"

    php-fpm:
        build: docker/php-fpm
        restart: always
        working_dir: /app
        links:
            - mariadb
        volumes:
            - ".:/app"
            - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf/666-overrides.ini"

    mariadb:
        image: mariadb
        restart: always
        working_dir: /app
        volumes:
            - ".:/app"
            - "./mariadb/data:/var/lib/mysql"
            - "./mariadb/logs:/var/log/mysql"
            - "./mariadb/conf:/etc/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
         - 8080:80
        environment:
          - PMA_ARBITRARY=1